- name: Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: www.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
