- name: Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: www.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}





- name: Declare a variable at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: www.example.com
